language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  # Set in the settings page of your repository, as a secure variable
  github_token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy"
  on:
    branch: master